sudo: required
language: node_js
branches:
  only:
    - master
    - next
matrix:
  include:
    - node_js: '10'
    - node_js: '11'
      if: head_branch IS blank AND branch = master
dist: out
cache:
  yarn: true
  directories:
    - node_modules
install:
  - npm install
before_script:
  # before scripts
script:
  - npm run export
before_cache:
  # nyc, jest and other projects store files in here. They mess up the travis build cache.
  - rm -rf ./node_modules/.cache/
after_success:
  # after success
deploy:
  provider: surge
  project: ./out
  domain: dvlp-haus.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
addons:
  chrome: stables
